//
//  Words.swift
//  Interesting Vocabulary Eng-Esp
//
//  Created by Umidjon Burhonov on 26/07/22.
//

import Foundation

import UIKit

struct Words {
    static let words = [
        WordsStruct(english: "a", spanish: "un, una"),
        WordsStruct(english: "abandon", spanish: "abandono, desenvoltura"),
        WordsStruct(english: "ablation", spanish: "ablación"),
        WordsStruct(english: "able", spanish: "capaz"),
        WordsStruct(english: "aboard", spanish: "a bordo "),
        WordsStruct(english: "abort", spanish: "abortar"),
        WordsStruct(english: "about", spanish: "alrededor de, junto a"),
        WordsStruct(english: "above", spanish: "encima"),
        WordsStruct(english: "above-board", spanish: "abiertamente"),
        WordsStruct(english: "abri", spanish: "cavidad"),
        WordsStruct(english: "abstain", spanish: "abstenerse de"),
        WordsStruct(english: "abstract", spanish: "abstracto"),
        WordsStruct(english: "academic", spanish: "académico, universitario"),
        WordsStruct(english: "academical", spanish: "teórico"),
        WordsStruct(english: "academy", spanish: "academia, colegio"),
        WordsStruct(english: "acarid", spanish: "acárido"),
        WordsStruct(english: "accent", spanish: "acento"),
        WordsStruct(english: "accentuation", spanish: "acentuación"),
        WordsStruct(english: "accompany", spanish: "acompañar"),
        WordsStruct(english: "accord", spanish: "acuerdo"),
        WordsStruct(english: "accordion", spanish: "acordeón"),
        WordsStruct(english: "accounting", spanish: "contabilidad, explicación"),
        WordsStruct(english: "accouter, accoutre", spanish: "vestir, ataviar"),
        WordsStruct(english: "Achaean", spanish: "aqueo"),
        WordsStruct(english: "act", spanish: "acto"),
        WordsStruct(english: "action", spanish: "acción"),
        WordsStruct(english: "activate", spanish: "activar"),
        WordsStruct(english: "activity", spanish: "actividad"),
        WordsStruct(english: "actor", spanish: "actor"),
        WordsStruct(english: "adapter", spanish: "adaptador"),
        WordsStruct(english: "add", spanish: "añadir"),
        WordsStruct(english: "add to", spanish: "aumentar"),
        WordsStruct(english: "adjust", spanish: "ajustar"),
        WordsStruct(english: "admin", spanish: "administración"),
        WordsStruct(english: "administration", spanish: "administración"),
        WordsStruct(english: "admission", spanish: "admisión"),
        WordsStruct(english: "admit", spanish: "admitir"),
        WordsStruct(english: "adult", spanish: "adulto"),
        WordsStruct(english: "advance", spanish: "adelanto"),
        WordsStruct(english: "adventure", spanish: "aventura"),
        WordsStruct(english: "aerobics", spanish: "aerobic"),
        WordsStruct(english: "afraid", spanish: "angustioso"),
        WordsStruct(english: "after", spanish: "después de;"),
        WordsStruct(english: "afternoon", spanish: "tarde"),
        WordsStruct(english: "aftershock", spanish: "réplica"),
        WordsStruct(english: "again", spanish: "de nuevo"),
        WordsStruct(english: "against", spanish: "contra"),
        WordsStruct(english: "age", spanish: "edad"),
        WordsStruct(english: "agent", spanish: "agente"),
        WordsStruct(english: "ago", spanish: "hace"),
        WordsStruct(english: "air", spanish: "aire"),
        WordsStruct(english: "Algeria", spanish: "Argelia"),
        WordsStruct(english: "Algerian", spanish: "argelino"),
        WordsStruct(english: "alignment", spanish: "alineación"),
        WordsStruct(english: "allow", spanish: "autorizar"),
        WordsStruct(english: "all-right", spanish: "bien"),
        WordsStruct(english: "alone", spanish: "sólo"),
        WordsStruct(english: "along", spanish: "a lo largo de "),
        WordsStruct(english: "already", spanish: "ya"),
        WordsStruct(english: "also", spanish: "asímismo"),
        WordsStruct(english: "always", spanish: "siempre"),
        WordsStruct(english: "America", spanish: "Estados Unidos"),
        WordsStruct(english: "American", spanish: "norteamericano"),
        WordsStruct(english: "among", spanish: "entre"),
        WordsStruct(english: "angle", spanish: "ángulo"),
        WordsStruct(english: "another", spanish: "otro"),
        WordsStruct(english: "any", spanish: "alguno"),
        WordsStruct(english: "bearea", spanish: "región"),
        WordsStruct(english: "array", spanish: "pompa"),
        WordsStruct(english: "Asia", spanish: "Asia"),
        WordsStruct(english: "Asian", spanish: "asiático"),
        WordsStruct(english: "ate", spanish: "pasado de eat"),
        WordsStruct(english: "August", spanish: "agosto"),
        WordsStruct(english: "author", spanish: "autor"),
        WordsStruct(english: "awful", spanish: "terrible, tremendo"),
        WordsStruct(english: "awl", spanish: "lezna"),
        WordsStruct(english: "axe", spanish: "hacha"),
        WordsStruct(english: "axis", spanish: "eje"),
        WordsStruct(english: "azure", spanish: "celeste"),
        WordsStruct(english: "baa", spanish: "balido,balar"),
        WordsStruct(english: "babe", spanish: "baby"),
        WordsStruct(english: "baby", spanish: "bebé, criatura"),
        WordsStruct(english: "back", spanish: "espalda"),
        WordsStruct(english: "backdoor", spanish: "clandestino"),
        WordsStruct(english: "back-up", spanish: "reserva, copia de seguridad"),
        WordsStruct(english: "badge", spanish: "señal"),
        WordsStruct(english: "badly", spanish: "mal, mucho"),
        WordsStruct(english: "baffle", spanish: "confusión"),
        WordsStruct(english: "bail", spanish: "fianza"),
        WordsStruct(english: "balance", spanish: "balanza"),
        WordsStruct(english: "ball", spanish: "nudillo"),
        WordsStruct(english: "Baltic", spanish: "báltico"),
        WordsStruct(english: "banner", spanish: "bandera"),
        WordsStruct(english: "barrow", spanish: "túmulo"),
        WordsStruct(english: "base", spanish: "fundamento, base"),
        WordsStruct(english: "baseball", spanish: "béisbol"),
        WordsStruct(english: "basic", spanish: "básico, fundamental"),
        WordsStruct(english: "basketball", spanish: "baloncesto"),
        WordsStruct(english: "bass", spanish: "bajo"),
        WordsStruct(english: "battery", spanish: "agresión"),
        WordsStruct(english: "battle", spanish: "batalla"),
        WordsStruct(english: "bawl", spanish: "gritar"),
        WordsStruct(english: "bear off", spanish: "llevarse"),
        WordsStruct(english: "bear on", spanish: "apuntar"),
        WordsStruct(english: "bear out", spanish: "confirmar"),
        WordsStruct(english: "bear up", spanish: "mantener firme"),
        WordsStruct(english: "beat off", spanish: "repeler"),
        WordsStruct(english: "beautiful", spanish: "hermoso"),
        WordsStruct(english: "beauty", spanish: "belleza"),
        WordsStruct(english: "became", spanish: "pasado de become"),
        WordsStruct(english: "bed", spanish: "cama, macizo"),
        WordsStruct(english: "bedroom", spanish: "dormitorio"),
        WordsStruct(english: "beet", spanish: "remolacha"),
        WordsStruct(english: "Belgium", spanish: "Bélgica"),
        WordsStruct(english: "believe", spanish: "creer"),
        WordsStruct(english: "belong (to)", spanish: "pertenecer"),
        WordsStruct(english: "below", spanish: "abajo"),
        WordsStruct(english: "bereft", spanish: "desolado"),
        WordsStruct(english: "besetting", spanish: "obsesivo"),
        WordsStruct(english: "beside", spanish: "junto a"),
        WordsStruct(english: "betray", spanish: "traicionar"),
        WordsStruct(english: "better", spanish: "mejor"),
        WordsStruct(english: "bicycle", spanish: "bicicleta"),
        WordsStruct(english: "big", spanish: "grande"),
        WordsStruct(english: "binary", spanish: "binario"),
        WordsStruct(english: "biology", spanish: "biología"),
        WordsStruct(english: "bird", spanish: "pájaro"),
        WordsStruct(english: "birthday", spanish: "cumpleaños"),
        WordsStruct(english: "biscuit§", spanish: "bizcocho"),
        WordsStruct(english: "black", spanish: "negro"),
        WordsStruct(english: "blackberry", spanish: "zarzamora"),
        WordsStruct(english: "block", spanish: "bloque"),
        WordsStruct(english: "blow", spanish: "golpe"),
        WordsStruct(english: "board", spanish: "tabla"),
        WordsStruct(english: "boat", spanish: "barca"),
        WordsStruct(english: "boil", spanish: "furúnculo"),
        WordsStruct(english: "bold", spanish: "audaz, enérgico"),
        WordsStruct(english: "book", spanish: "libro"),
        WordsStruct(english: "boot", spanish: "bota"),
        WordsStruct(english: "bottle", spanish: "botella"),
        WordsStruct(english: "bottom", spanish: "fondo"),
        WordsStruct(english: "boutique", spanish: "boutique"),
        WordsStruct(english: "bowl", spanish: "taza"),
        WordsStruct(english: "box", spanish: "caja"),
        WordsStruct(english: "boyfriend", spanish: "amigo"),
        WordsStruct(english: "bracelet", spanish: "pulsera"),
        WordsStruct(english: "brain", spanish: "cerebro"),
        WordsStruct(english: "branch", spanish: "rama"),
        WordsStruct(english: "bread", spanish: "pan"),
        WordsStruct(english: "break", spanish: "grieta"),
        WordsStruct(english: "brewery", spanish: "cervecería"),
        WordsStruct(english: "brigade", spanish: "brigada"),
        WordsStruct(english: "bring", spanish: "llevar"),
        WordsStruct(english: "broach", spanish: "mencionar por primera vez"),
        WordsStruct(english: "broad", spanish: "ancho"),
        WordsStruct(english: "broth", spanish: "caldo"),
        WordsStruct(english: "brown", spanish: "marrón"),
        WordsStruct(english: "brush", spanish: "brocha"),
        WordsStruct(english: "bucket", spanish: "balde"),
        WordsStruct(english: "buffet", spanish: "cafetería"),
        WordsStruct(english: "build", spanish: "complexión"),
        WordsStruct(english: "bull", spanish: "toro"),
        WordsStruct(english: "bump", spanish: "golpe"),
        WordsStruct(english: "bundle", spanish: "fajo"),
        WordsStruct(english: "bunker", spanish: "carbonera"),
        WordsStruct(english: "buster", spanish: "tío"),
        WordsStruct(english: "button", spanish: "botón"),
        WordsStruct(english: "buy", spanish: "compra"),
        WordsStruct(english: "buzz", spanish: "rumor"),
        WordsStruct(english: "bye, bye-bye", spanish: "adiós"),
        WordsStruct(english: "cab", spanish: "taxi"),
        WordsStruct(english: "cabbage", spanish: "col, repollo"),
        WordsStruct(english: "cabinet", spanish: "gabinete"),
        WordsStruct(english: "cache", spanish: "escondite"),
        WordsStruct(english: "cafe", spanish: "bar, cafetería"),
        WordsStruct(english: "cage", spanish: "jaula"),
        WordsStruct(english: "cake", spanish: "pastel"),
        WordsStruct(english: "calamine", spanish: "calamina"),
        WordsStruct(english: "calculate", spanish: "calcular"),
        WordsStruct(english: "calf", spanish: "pantorrilla"),
        WordsStruct(english: "call", spanish: "llamada, canto"),
        WordsStruct(english: "call off", spanish: "suspender"),
        WordsStruct(english: "call up", spanish: "telefonear"),
        WordsStruct(english: "cam", spanish: "leva"),
        WordsStruct(english: "camera", spanish: "cámara"),
        WordsStruct(english: "cameraman", spanish: "cámara"),
        WordsStruct(english: "campion", spanish: "colleja"),
        WordsStruct(english: "cancel", spanish: "anular"),
        WordsStruct(english: "candy", spanish: "bombón"),
        WordsStruct(english: "cane", spanish: "bastón"),
        WordsStruct(english: "canteen", spanish: "cantina"),
        WordsStruct(english: "capital", spanish: "vital"),
        WordsStruct(english: "capitalism", spanish: "capitalismo"),
        WordsStruct(english: "captain", spanish: "capitán"),
        WordsStruct(english: "caravan", spanish: "remolque"),
        WordsStruct(english: "card", spanish: "programa"),
        WordsStruct(english: "careful", spanish: "cuidadoso"),
        WordsStruct(english: "carnival", spanish: "carnaval"),
        WordsStruct(english: "carry", spanish: "conducir"),
        WordsStruct(english: "cartel", spanish: "cártel"),
        WordsStruct(english: "carton", spanish: "caja de cartón"),
        WordsStruct(english: "cartoon", spanish: "dibujos animados"),
        WordsStruct(english: "case", spanish: "caja"),
        WordsStruct(english: "cash", spanish: "dinero en efectivo"),
        WordsStruct(english: "cask", spanish: "tonel"),
        WordsStruct(english: "casting", spanish: "reparto de papeles"),
        WordsStruct(english: "casually", spanish: "con aire de naturalidad "),
        WordsStruct(english: "cat", spanish: "gato"),
        WordsStruct(english: "catch", spanish: "trampa"),
        WordsStruct(english: "caw", spanish: "graznido"),
        WordsStruct(english: "celebrate", spanish: "celebrar"),
        WordsStruct(english: "cell", spanish: "celda"),
        WordsStruct(english: "cent", spanish: "centavo"),
        WordsStruct(english: "certain", spanish: "cierto"),
        WordsStruct(english: "certificate", spanish: "acta, certificación"),
        WordsStruct(english: "chair", spanish: "silla"),
        WordsStruct(english: "chalk", spanish: "cretatiza"),
        WordsStruct(english: "challenge", spanish: "desafío"),
        WordsStruct(english: "champion", spanish: "campeón"),
        WordsStruct(english: "change", spanish: "cambio"),
        WordsStruct(english: "channel", spanish: "canal"),
        WordsStruct(english: "character", spanish: "referencias"),
        WordsStruct(english: "charge", spanish: "encargo"),
        WordsStruct(english: "charger", spanish: "caballo de guerra"),
        WordsStruct(english: "chart", spanish: "gráfico"),
        WordsStruct(english: "check", spanish: "escaque"),
        WordsStruct(english: "check in", spanish: "inscribirse, registrarse"),
        WordsStruct(english: "cheep", spanish: "pío, piar"),
        WordsStruct(english: "cheer", spanish: "viva"),
        WordsStruct(english: "cheese", spanish: "queso"),
        WordsStruct(english: "chemist", spanish: "farmacia"),
        WordsStruct(english: "chess", spanish: "ajedrez"),
        WordsStruct(english: "chicken", spanish: "pollo"),
        WordsStruct(english: "chrome", spanish: "cromo"),
        WordsStruct(english: "circular", spanish: "circular"),
        WordsStruct(english: "citizen", spanish: "ciudadano"),
        WordsStruct(english: "clapper", spanish: "badajo"),
        WordsStruct(english: "clash", spanish: "choque, enfrentamiento"),
        WordsStruct(english: "class", spanish: "clase"),
        WordsStruct(english: "classroom", spanish: "clase"),
        WordsStruct(english: "clean", spanish: "completamente"),
        WordsStruct(english: "clear", spanish: "claro"),
        WordsStruct(english: "clever", spanish: "astuto"),
        WordsStruct(english: "clinic", spanish: "dispensario"),
        WordsStruct(english: "clips", spanish: "pasador"),
        WordsStruct(english: "clone", spanish: "clon"),
        WordsStruct(english: "close", spanish: "recinto"),
        WordsStruct(english: "closure", spanish: "fin"),
        WordsStruct(english: "cloudy", spanish: "cubierto"),
        WordsStruct(english: "coast", spanish: "costa"),
        WordsStruct(english: "code", spanish: "código"),
        WordsStruct(english: "coffee", spanish: "café"),
        WordsStruct(english: "collection", spanish: "colección"),
        WordsStruct(english: "color", spanish: "color"),
        WordsStruct(english: "come", spanish: "venir"),
        WordsStruct(english: "come back", spanish: "volver"),
        WordsStruct(english: "comfort", spanish: "consuelo"),
        WordsStruct(english: "comfortable", spanish: "cómodo"),
        WordsStruct(english: "common", spanish: "común"),
        WordsStruct(english: "communicate", spanish: "comunicar"),
        WordsStruct(english: "compare", spanish: "comparar"),
        WordsStruct(english: "concern", spanish: "interés"),
        WordsStruct(english: "confirm", spanish: "confirmar"),
        WordsStruct(english: "confuse", spanish: "confundir"),
        WordsStruct(english: "conservation", spanish: "conservación"),
        WordsStruct(english: "conserve", spanish: "conservar"),
        WordsStruct(english: "consul", spanish: "cónsul"),
        WordsStruct(english: "consultant", spanish: "especialista"),
        WordsStruct(english: "cook", spanish: "cocinero"),
        WordsStruct(english: "cooker", spanish: "cocina"),
        WordsStruct(english: "cool", spanish: "calma"),
        WordsStruct(english: "cost", spanish: "coste"),
        WordsStruct(english: "costumer", spanish: "sastre de teatro"),
        WordsStruct(english: "counter", spanish: "ficha"),
        WordsStruct(english: "cover up", spanish: "cubrir completamente"),
        WordsStruct(english: "cowboy", spanish: "vaquero"),
        WordsStruct(english: "craft", spanish: "arte"),
        WordsStruct(english: "craze", spanish: "resquebrajadura"),
        WordsStruct(english: "crazy", spanish: "loco"),
        WordsStruct(english: "cross", spanish: "cruz"),
        WordsStruct(english: "cry", spanish: "grito"),
        WordsStruct(english: "culture", spanish: "cultivo"),
        WordsStruct(english: "curly", spanish: "rizado"),
        WordsStruct(english: "current", spanish: "corriente"),
        WordsStruct(english: "custom", spanish: "costumbre"),
        WordsStruct(english: "cycle", spanish: "bicicleta"),
        WordsStruct(english: "cynic", spanish: "cínico"),
        WordsStruct(english: "czar", spanish: "zar"),
        WordsStruct(english: "Czech", spanish: "checo"),
        WordsStruct(english: "dad", spanish: "papá"),
        WordsStruct(english: "dairy", spanish: "lechería"),
        WordsStruct(english: "damage", spanish: "daño"),
        WordsStruct(english: "dance", spanish: "baile"),
        WordsStruct(english: "danger", spanish: "peligro"),
        WordsStruct(english: "dark", spanish: "oscuridad"),
        WordsStruct(english: "dash", spanish: "poquito"),
        WordsStruct(english: "date", spanish: "novio"),
        WordsStruct(english: "data", spanish: "dato"),
        WordsStruct(english: "deal", spanish: "trato"),
        WordsStruct(english: "dear", spanish: "caro"),
        WordsStruct(english: "decide", spanish: "decidir"),
        WordsStruct(english: "decision", spanish: "decisión"),
        WordsStruct(english: "define", spanish: "definir"),
        WordsStruct(english: "degrade", spanish: "degradar"),
        WordsStruct(english: "dell", spanish: "vallecito"),
        WordsStruct(english: "demo", spanish: "manifestación"),
        WordsStruct(english: "dentist", spanish: "dentista"),
        WordsStruct(english: "depart", spanish: "partir"),
        WordsStruct(english: "depend", spanish: "depender"),
        WordsStruct(english: "desert", spanish: "desierto"),
        WordsStruct(english: "desire", spanish: "deseo"),
        WordsStruct(english: "destination", spanish: "destino"),
        WordsStruct(english: "destroy", spanish: "destruir"),
        WordsStruct(english: "devote", spanish: "dedicar"),
        WordsStruct(english: "dictation", spanish: "dictado"),
        WordsStruct(english: "dirt", spanish: "suciedad"),
        WordsStruct(english: "dirty", spanish: "sucio"),
        WordsStruct(english: "dock", spanish: "muelle"),
        WordsStruct(english: "doctor", spanish: "doctor"),
        WordsStruct(english: "donkey", spanish: "burro"),
        WordsStruct(english: "during", spanish: "durante"),
        WordsStruct(english: "drag", spanish: "calada"),
        WordsStruct(english: "dream", spanish: "sueño"),
        WordsStruct(english: "drop", spanish: "gota"),
        WordsStruct(english: "dry", spanish: "seco"),
        WordsStruct(english: "dying", spanish: "final"),
        WordsStruct(english: "dynamic", spanish: "dinámico"),
        WordsStruct(english: "dyslexic", spanish: "disléxico"),
        WordsStruct(english: "each", spanish: "cada"),
        WordsStruct(english: "eager", spanish: "ansioso"),
        WordsStruct(english: "earn", spanish: "ganar"),
        WordsStruct(english: "earth", spanish: "tierra"),
        WordsStruct(english: "east", spanish: "este"),
        WordsStruct(english: "echo", spanish: "eco"),
        WordsStruct(english: "edge", spanish: "ventaja"),
        WordsStruct(english: "edit", spanish: "revisar"),
        WordsStruct(english: "effect", spanish: "effecto"),
        WordsStruct(english: "egg", spanish: "huevo"),
        WordsStruct(english: "either", spanish: "alguno"),
        WordsStruct(english: "electric", spanish: "eléctrico"),
        WordsStruct(english: "electronic", spanish: "electrónico"),
        WordsStruct(english: "elegant", spanish: "elegante"),
        WordsStruct(english: "else", spanish: "si no"),
        WordsStruct(english: "emblem", spanish: "emblema"),
        WordsStruct(english: "emotion", spanish: "emoción"),
        WordsStruct(english: "empire", spanish: "imperio"),
        WordsStruct(english: "employer", spanish: "patrón"),
        WordsStruct(english: "empty", spanish: "vacío"),
        WordsStruct(english: "enable:", spanish: "permitir"),
        WordsStruct(english: "end", spanish: "extremo"),
        WordsStruct(english: "energy", spanish: "energía"),
        WordsStruct(english: "enough", spanish: "suficiente"),
        WordsStruct(english: "ensure", spanish: "asegurar"),
        WordsStruct(english: "enter", spanish: "anotar"),
        WordsStruct(english: "entry", spanish: "anotación"),
        WordsStruct(english: "epic", spanish: "epopeya"),
        WordsStruct(english: "epigraph", spanish: "epígrafe"),
        WordsStruct(english: "episode", spanish: "episodio"),
        WordsStruct(english: "equal", spanish: "equitativo"),
        WordsStruct(english: "equinox", spanish: "equinoccio"),
        WordsStruct(english: "escalate", spanish: "agravarse"),
        WordsStruct(english: "escape", spanish: "escape"),
        WordsStruct(english: "especially", spanish: "especialmente"),
        WordsStruct(english: "essential", spanish: "esencial9"),
        WordsStruct(english: "even", spanish: "sereno"),
        WordsStruct(english: "everybody", spanish: "todos"),
        WordsStruct(english: "everyday", spanish: "cotidiano"),
        WordsStruct(english: "everything", spanish: "todo"),
        WordsStruct(english: "everywhere", spanish: "por todas partes"),
        WordsStruct(english: "exactly", spanish: "exactamente"),
        WordsStruct(english: "examine", spanish: "examinar"),
        WordsStruct(english: "excellent", spanish: "excelente"),
        WordsStruct(english: "except", spanish: "excepto"),
        WordsStruct(english: "excite", spanish: "excitar"),
        WordsStruct(english: "exercise", spanish: "ejercicio"),
        WordsStruct(english: "eye", spanish: "ojo"),
        WordsStruct(english: "eyebrow", spanish: "ceja"),
        WordsStruct(english: "fable", spanish: "fábula"),
        WordsStruct(english: "face", spanish: "cara"),
        WordsStruct(english: "faculty", spanish: "aptitud"),
        WordsStruct(english: "fail", spanish: "suspenso"),
        WordsStruct(english: "fair", spanish: "feria"),
        WordsStruct(english: "fake", spanish: "falsificación"),
        WordsStruct(english: "falcon", spanish: "halcón"),
        WordsStruct(english: "fall", spanish: "otoño"),
        WordsStruct(english: "false", spanish: "falso"),
        WordsStruct(english: "family", spanish: "familia"),
        WordsStruct(english: "famous", spanish: "famoso"),
        WordsStruct(english: "fantastic, fantastical", spanish: "fantástico"),
        WordsStruct(english: "father", spanish: "padre"),
        WordsStruct(english: "feel", spanish: "tacto"),
        WordsStruct(english: "female", spanish: "femenino"),
        WordsStruct(english: "ferry", spanish: "transbordador"),
        WordsStruct(english: "few", spanish: "poco"),
        WordsStruct(english: "fifteen", spanish: "quince"),
        WordsStruct(english: "fifteenth", spanish: "decimoquinto"),
        WordsStruct(english: "fifth", spanish: "decimoquinto"),
        WordsStruct(english: "fifty", spanish: "cincuenta"),
        WordsStruct(english: "figure", spanish: "número"),
        WordsStruct(english: "fill", spanish: "llenar, tapar"),
        WordsStruct(english: "film", spanish: "película"),
        WordsStruct(english: "filter", spanish: "filtro"),
        WordsStruct(english: "fine", spanish: "multa"),
        WordsStruct(english: "fingerprint", spanish: "huella dactilar"),
        WordsStruct(english: "finish", spanish: "meta"),
        WordsStruct(english: "fire", spanish: "fuego"),
        WordsStruct(english: "fish", spanish: "pez"),
        WordsStruct(english: "fix", spanish: "aprieto"),
        WordsStruct(english: "five", spanish: "cinco"),
        WordsStruct(english: "flag", spanish: "bandera"),
        WordsStruct(english: "flamingo", spanish: "flamenco"),
        WordsStruct(english: "flap", spanish: "hoja plegadiza"),
        WordsStruct(english: "flashlight", spanish: "linterna eléctrica"),
        WordsStruct(english: "flat", spanish: "llanura"),
        WordsStruct(english: "flesh", spanish: "carne"),
        WordsStruct(english: "flower", spanish: "flor"),
        WordsStruct(english: "fly", spanish: "mosca"),
        WordsStruct(english: "fog", spanish: "niebla"),
        WordsStruct(english: "follow", spanish: "seguir"),
        WordsStruct(english: "food", spanish: "materia"),
        WordsStruct(english: "football", spanish: "fútbol"),
        WordsStruct(english: "force", spanish: "fuerza"),
        WordsStruct(english: "forest", spanish: "bosque"),
        WordsStruct(english: "forget", spanish: "olvidar"),
        WordsStruct(english: "forty", spanish: "cuarenta"),
        WordsStruct(english: "found", spanish: "fundar"),
        WordsStruct(english: "four", spanish: "cuatro"),
        WordsStruct(english: "fourth", spanish: "cuarto"),
        WordsStruct(english: "frame", spanish: "marco"),
        WordsStruct(english: "free", spanish: "libre"),
        WordsStruct(english: "freeze", spanish: "helada"),
        WordsStruct(english: "frequency", spanish: "frecuencia"),
        WordsStruct(english: "frequently", spanish: "frecuentemente"),
        WordsStruct(english: "Friday", spanish: "viernes"),
        WordsStruct(english: "fridge", spanish: "frigorífico"),
        WordsStruct(english: "friend", spanish: "amigo"),
        WordsStruct(english: "friendship", spanish: "amistad"),
        WordsStruct(english: "frog", spanish: "rana"),
        WordsStruct(english: "from", spanish: "desde"),
        WordsStruct(english: "front", spanish: "fachada"),
        WordsStruct(english: "froze", spanish: "helado"),
        WordsStruct(english: "freeze, frozen", spanish: "helado"),
        WordsStruct(english: "fruit", spanish: "fruta"),
        WordsStruct(english: "fuck", spanish: "polvo"),
        WordsStruct(english: "fudge", spanish: "embuste"),
        WordsStruct(english: "fug", spanish: "aire viciado"),
        WordsStruct(english: "full", spanish: "absorto"),
        WordsStruct(english: "fullback", spanish: "defensa"),
        WordsStruct(english: "fun", spanish: "broma"),
        WordsStruct(english: "function", spanish: "función"),
        WordsStruct(english: "further", spanish: "adicional"),
        WordsStruct(english: "fuse", spanish: "fusible"),
        WordsStruct(english: "gadget", spanish: "chisme"),
        WordsStruct(english: "gadwall", spanish: "ánade friso"),
        WordsStruct(english: "gain", spanish: "ganancia"),
        WordsStruct(english: "gait", spanish: "paso"),
        WordsStruct(english: "gambit", spanish: "táctica"),
        WordsStruct(english: "gap", spanish: "hueco"),
        WordsStruct(english: "garden", spanish: "jardín"),
        WordsStruct(english: "gastronomic§", spanish: "gastronómico"),
        WordsStruct(english: "gateway", spanish: "entrada"),
        WordsStruct(english: "gather", spanish: "juntar"),
        WordsStruct(english: "gave", spanish: "pasado de give"),
        WordsStruct(english: "gen", spanish: "información"),
        WordsStruct(english: "gender", spanish: "género"),
        WordsStruct(english: "general", spanish: "general"),
        WordsStruct(english: "generate", spanish: "generar"),
        WordsStruct(english: "genius", spanish: "genio"),
        WordsStruct(english: "genre", spanish: "género"),
        WordsStruct(english: "geography", spanish: "geografía"),
        WordsStruct(english: "geometry", spanish: "geometría"),
        WordsStruct(english: "gerund", spanish: "gerundio"),
        WordsStruct(english: "get", spanish: "detener"),
        WordsStruct(english: "get in", spanish: "entrar"),
        WordsStruct(english: "get on", spanish: "adelantar"),
        WordsStruct(english: "ghost", spanish: "fantasma"),
        WordsStruct(english: "gibber", spanish: "farfullar"),
        WordsStruct(english: "gift", spanish: "talento"),
        WordsStruct(english: "girl", spanish: "chica"),
        WordsStruct(english: "girlfriend", spanish: "novia"),
        WordsStruct(english: "git", spanish: "bobo"),
        WordsStruct(english: "give", spanish: "elasticidad"),
        WordsStruct(english: "glacé", spanish: "escarchado"),
        WordsStruct(english: "gladiator", spanish: "gladiador"),
        WordsStruct(english: "glamour", spanish: "encanto"),
        WordsStruct(english: "glass", spanish: "vaso"),
        WordsStruct(english: "glasses", spanish: "gafas"),
        WordsStruct(english: "glob", spanish: "masa pequeña"),
        WordsStruct(english: "glory", spanish: "elogio"),
        WordsStruct(english: "go", spanish: "intento"),
        WordsStruct(english: "go away", spanish: "irse"),
        WordsStruct(english: "goal", spanish: "meta"),
        WordsStruct(english: "goat", spanish: "macho cabrío"),
        WordsStruct(english: "goblin", spanish: "trasgo"),
        WordsStruct(english: "godfather", spanish: "padrino"),
        WordsStruct(english: "going", spanish: "partida"),
        WordsStruct(english: "gold", spanish: "oro"),
        WordsStruct(english: "golden", spanish: "dorado"),
        WordsStruct(english: "golf", spanish: "golf"),
        WordsStruct(english: "good", spanish: "bueno"),
        WordsStruct(english: "goodbye", spanish: "adiós"),
        WordsStruct(english: "good-looking", spanish: "bien parecido"),
        WordsStruct(english: "goose", spanish: "oca"),
        WordsStruct(english: "grace", spanish: "gracia"),
        WordsStruct(english: "grade", spanish: "grado"),
        WordsStruct(english: "graduate", spanish: "licenciado"),
        WordsStruct(english: "grape", spanish: "uva"),
        WordsStruct(english: "gravity", spanish: "gravedad"),
        WordsStruct(english: "Greece", spanish: "Grecia"),
        WordsStruct(english: "green", spanish: "verde"),
        WordsStruct(english: "grip", spanish: "agarre"),
        WordsStruct(english: "gross", spanish: "enorme"),
        WordsStruct(english: "group", spanish: "grupo"),
        WordsStruct(english: "grow", spanish: "crecer"),
        WordsStruct(english: "grown", spanish: "adulto"),
        WordsStruct(english: "guard", spanish: "guardia"),
        WordsStruct(english: "guess", spanish: "conjetura"),
        WordsStruct(english: "guide", spanish: "guía"),
        WordsStruct(english: "gun", spanish: "cañón"),
        WordsStruct(english: "gymnastics", spanish: "gimnasia"),
        WordsStruct(english: "gyp", spanish: "estafar"),
        WordsStruct(english: "ha", spanish: "ah!"),
        WordsStruct(english: "habit", spanish: "hábito"),
        WordsStruct(english: "hack", spanish: "taxi"),
        WordsStruct(english: "hacker", spanish: "pirata informático"),
        WordsStruct(english: "hacking", spanish: "seco"),
        WordsStruct(english: "haft", spanish: "mango"),
        WordsStruct(english: "hail", spanish: "granizo"),
        WordsStruct(english: "hair", spanish: "pelo"),
        WordsStruct(english: "half", spanish: "mitad"),
        WordsStruct(english: "hall", spanish: "sala"),
        WordsStruct(english: "ham", spanish: "jamón cocido"),
        WordsStruct(english: "hamlet", spanish: "aldea"),
        WordsStruct(english: "hand", spanish: "mano"),
        WordsStruct(english: "handbell", spanish: "campanilla"),
        WordsStruct(english: "handbook", spanish: "manual"),
        WordsStruct(english: "hang", spanish: "tranquillo"),
        WordsStruct(english: "happy", spanish: "feliz"),
        WordsStruct(english: "happen", spanish: "pasar"),
        WordsStruct(english: "hard", spanish: "duro"),
        WordsStruct(english: "harp", spanish: "arpa"),
        WordsStruct(english: "hat", spanish: "sombrero"),
        WordsStruct(english: "have", spanish: "haber"),
        WordsStruct(english: "head", spanish: "cabeza"),
        WordsStruct(english: "hear", spanish: "oír"),
        WordsStruct(english: "heart", spanish: "corazón"),
        WordsStruct(english: "heaven", spanish: "cielo"),
        WordsStruct(english: "hell", spanish: "infierno"),
        WordsStruct(english: "hello", spanish: "hola"),
        WordsStruct(english: "help", spanish: "ayuda"),
        WordsStruct(english: "hen", spanish: "gallina"),
        WordsStruct(english: "henry", spanish: "henrio"),
        WordsStruct(english: "hero", spanish: "héroe"),
        WordsStruct(english: "hi", spanish: "hola"),
        WordsStruct(english: "hide", spanish: "cuero"),
        WordsStruct(english: "high", spanish: "alto"),
        WordsStruct(english: "hike", spanish: "caminata"),
        WordsStruct(english: "hint", spanish: "indicación"),
        WordsStruct(english: "hire", spanish: "alquiler"),
        WordsStruct(english: "history", spanish: "historia"),
        WordsStruct(english: "hold", spanish: "fortaleza"),
        WordsStruct(english: "hole", spanish: "agujero"),
        WordsStruct(english: "holiday", spanish: "fiesta"),
        WordsStruct(english: "honey", spanish: "miel"),
        WordsStruct(english: "hood", spanish: "capó"),
        WordsStruct(english: "horse", spanish: "caballo"),
        WordsStruct(english: "hose", spanish: "manguera"),
        WordsStruct(english: "hospital", spanish: "hospital"),
        WordsStruct(english: "host", spanish: "hostia"),
        WordsStruct(english: "household", spanish: "casa"),
        WordsStruct(english: "how", spanish: "cómo"),
        WordsStruct(english: "huge", spanish: "enorme"),
        WordsStruct(english: "human", spanish: "humano"),
        WordsStruct(english: "hung", spanish: "pasado"),
        WordsStruct(english: "hungry", spanish: "hambriento"),
        WordsStruct(english: "hunt", spanish: "caza"),
        WordsStruct(english: "hurt", spanish: "herido"),
        WordsStruct(english: "hutch", spanish: "arca"),
        WordsStruct(english: "hyacinth", spanish: "jacinto"),
        WordsStruct(english: "hygiene", spanish: "higiene"),
        WordsStruct(english: "I", spanish: "yo"),
        WordsStruct(english: "ice", spanish: "hielo"),
        WordsStruct(english: "icon", spanish: "icono"),
        WordsStruct(english: "idea", spanish: "concepto"),
        WordsStruct(english: "ideal", spanish: "ideal"),
        WordsStruct(english: "identify", spanish: "identificar"),
        WordsStruct(english: "idiom", spanish: "idioma"),
        WordsStruct(english: "if", spanish: "si"),
        WordsStruct(english: "ignore", spanish: "ignorar"),
        WordsStruct(english: "image", spanish: "imagen"),
        WordsStruct(english: "immutable", spanish: "inmutable"),
        WordsStruct(english: "impend", spanish: "cernerse"),
        WordsStruct(english: "imperative", spanish: "imperativo"),
        WordsStruct(english: "imply", spanish: "implicar"),
        WordsStruct(english: "in", spanish: "dentro"),
        WordsStruct(english: "inception", spanish: "comienzo"),
        WordsStruct(english: "incision", spanish: "incisión"),
        WordsStruct(english: "including", spanish: "inclusive"),
        WordsStruct(english: "increase", spanish: "aumento"),
        WordsStruct(english: "indicator", spanish: "indicator"),
        WordsStruct(english: "initial", spanish: "inicial"),
        WordsStruct(english: "injection", spanish: "inyección"),
        WordsStruct(english: "inset", spanish: "grabado"),
        WordsStruct(english: "interesting", spanish: "interesante"),
        WordsStruct(english: "introduce", spanish: "introducir"),
        WordsStruct(english: "issue", spanish: "asunto"),
        WordsStruct(english: "it", spanish: "lo"),
        WordsStruct(english: "jack", spanish: "gato"),
        WordsStruct(english: "jag", spanish: "punta"),
        WordsStruct(english: "jail", spanish: "cárcel"),
        WordsStruct(english: "jargon", spanish: "jerga"),
        WordsStruct(english: "jingo", spanish: "patriotería"),
        WordsStruct(english: "job", spanish: "empleo"),
        WordsStruct(english: "jockey", spanish: "jockey"),
        WordsStruct(english: "jog", spanish: "empujoncito"),
        WordsStruct(english: "join", spanish: "punto de unión o encuentro"),
        WordsStruct(english: "journal", spanish: "diario"),
        WordsStruct(english: "juice", spanish: "zumo"),
        WordsStruct(english: "justice", spanish: "juez"),
        WordsStruct(english: "kangaroo", spanish: "canguro"),
        WordsStruct(english: "kedge", spanish: "anclote"),
        WordsStruct(english: "keep", spanish: "fortaleza"),
        WordsStruct(english: "kettle", spanish: "caldero"),
        WordsStruct(english: "key", spanish: "llave"),
        WordsStruct(english: "keynote", spanish: "de apertura"),
        WordsStruct(english: "kick", spanish: "patada"),
        WordsStruct(english: "kid", spanish: "cabritilla"),
        WordsStruct(english: "kind", spanish: "clase"),
        WordsStruct(english: "king", spanish: "rey"),
        WordsStruct(english: "kingdom", spanish: "reino"),
        WordsStruct(english: "kleptomania", spanish: "cleptomanía"),
        WordsStruct(english: "knife", spanish: "cuchillo"),
        WordsStruct(english: "knock-on", spanish: "en cadena"),
        WordsStruct(english: "know", spanish: "conocer"),
        WordsStruct(english: "knowledge", spanish: "conocimiento"),
        WordsStruct(english: "krone", spanish: "corona"),
        WordsStruct(english: "label", spanish: "rótulo"),
        WordsStruct(english: "labour", spanish: "balanceo"),
        WordsStruct(english: "lady", spanish: "señora"),
        WordsStruct(english: "lake", spanish: "lago"),
        WordsStruct(english: "lamb", spanish: "cordero"),
        WordsStruct(english: "land", spanish: "tierra"),
        WordsStruct(english: "landscape", spanish: "paisaje"),
        WordsStruct(english: "language", spanish: "lengua"),
        WordsStruct(english: "laptop", spanish: "ordenador portátil plegable"),
        WordsStruct(english: "large", spanish: "espacioso"),
        WordsStruct(english: "last", spanish: "precedente"),
        WordsStruct(english: "late", spanish: "difunto"),
        WordsStruct(english: "laugh", spanish: "risa"),
        WordsStruct(english: "launch", spanish: "lanzamiento"),
        WordsStruct(english: "law", spanish: "derecho"),
        WordsStruct(english: "layer", spanish: "capa"),
        WordsStruct(english: "lazy", spanish: "perezoso"),
        WordsStruct(english: "leader", spanish: "jefe"),
        WordsStruct(english: "league", spanish: "legua"),
        WordsStruct(english: "learn", spanish: "aprender"),
        WordsStruct(english: "leave", spanish: "licencia"),
        WordsStruct(english: "lees", spanish: "heces"),
        WordsStruct(english: "left", spanish: "izquierdo"),
        WordsStruct(english: "leg", spanish: "pierna"),
        WordsStruct(english: "legion", spanish: "legión"),
        WordsStruct(english: "let", spanish: "estorbo"),
        WordsStruct(english: "letter", spanish: "carta"),
        WordsStruct(english: "level", spanish: "llanura"),
        WordsStruct(english: "licorice", spanish: "regaliz"),
        WordsStruct(english: "lie", spanish: "disposición"),
        WordsStruct(english: "light", spanish: "ilustración"),
        WordsStruct(english: "like", spanish: "semejante"),
        WordsStruct(english: "lime", spanish: "cal"),
        WordsStruct(english: "limit", spanish: "límite"),
        WordsStruct(english: "line", spanish: "cordón"),
        WordsStruct(english: "lion", spanish: "león"),
        WordsStruct(english: "liquid", spanish: "líquido"),
        WordsStruct(english: "list", spanish: "lista"),
        WordsStruct(english: "listen", spanish: "escuchar"),
        WordsStruct(english: "live", spanish: "vivo"),
        WordsStruct(english: "load", spanish: "carga"),
        WordsStruct(english: "local", spanish: "vecino"),
        WordsStruct(english: "locate", spanish: "localizar"),
        WordsStruct(english: "location", spanish: "ubicación"),
        WordsStruct(english: "lock", spanish: "mechón"),
        WordsStruct(english: "log", spanish: "tronco"),
        WordsStruct(english: "log out", spanish: "salir"),
        WordsStruct(english: "logic", spanish: "lógica"),
        WordsStruct(english: "logo", spanish: "logotipo"),
        WordsStruct(english: "long", spanish: "largo"),
        WordsStruct(english: "look", spanish: "aspecto"),
        WordsStruct(english: "loop", spanish: "lazo"),
        WordsStruct(english: "lord", spanish: "lord"),
        WordsStruct(english: "lose", spanish: "perder"),
        WordsStruct(english: "lot", spanish: "solar"),
        WordsStruct(english: "loud", spanish: "alto"),
        WordsStruct(english: "love", spanish: "amor"),
        WordsStruct(english: "lovely", spanish: "guapa"),
        WordsStruct(english: "low", spanish: "borrasca"),
        WordsStruct(english: "lunch", spanish: "almuerzo"),
        WordsStruct(english: "lune", spanish: "lúnula"),
        WordsStruct(english: "luxurious", spanish: "lujoso"),
        WordsStruct(english: "luxury", spanish: "artículo de lujo"),
        WordsStruct(english: "lyceum", spanish: "liceo"),
        WordsStruct(english: "mac", spanish: "impermeable"),
        WordsStruct(english: "machine", spanish: "aparato"),
        WordsStruct(english: "magazine", spanish: "recámara"),
        WordsStruct(english: "magic", spanish: "magia"),
        WordsStruct(english: "mailbox", spanish: "buzón"),
        WordsStruct(english: "main", spanish: "mayor"),
        WordsStruct(english: "major", spanish: "especialidad"),
        WordsStruct(english: "make", spanish: "marca"),
        WordsStruct(english: "male", spanish: "macho"),
        WordsStruct(english: "man", spanish: "hombre"),
        WordsStruct(english: "manager", spanish: "director"),
        WordsStruct(english: "manic", spanish: "maníaco"),
        WordsStruct(english: "map", spanish: "carta"),
        WordsStruct(english: "march", spanish: "marcha"),
        WordsStruct(english: "March", spanish: "marzo"),
        WordsStruct(english: "married", spanish: "casado"),
        WordsStruct(english: "marry", spanish: "casar"),
        WordsStruct(english: "massage", spanish: "masaje"),
        WordsStruct(english: "math", spanish: "cuenta"),
        WordsStruct(english: "maximum", spanish: "máximo"),
        WordsStruct(english: "me", spanish: "me"),
        WordsStruct(english: "meal", spanish: "comida"),
        WordsStruct(english: "mean", spanish: "promedio"),
        WordsStruct(english: "medic", spanish: "médico"),
        WordsStruct(english: "memory", spanish: "memoria"),
        WordsStruct(english: "menu", spanish: "menú"),
        WordsStruct(english: "meteor", spanish: "meteoro"),
        WordsStruct(english: "microphone", spanish: "micrófono"),
        WordsStruct(english: "middle", spanish: "cintura"),
        WordsStruct(english: "midway", spanish: "camino central"),
        WordsStruct(english: "minimum", spanish: "mínimo"),
        WordsStruct(english: "minion", spanish: "esbirro"),
        WordsStruct(english: "mission", spanish: "misión"),
        WordsStruct(english: "mister", spanish: "señor"),
        WordsStruct(english: "mobile", spanish: "móvil"),
        WordsStruct(english: "Monday", spanish: "lunes"),
        WordsStruct(english: "money", spanish: "dinero"),
        WordsStruct(english: "month", spanish: "mes"),
        WordsStruct(english: "mooring", spanish: "amarradero"),
        WordsStruct(english: "more", spanish: "más"),
        WordsStruct(english: "mother", spanish: "madre"),
        WordsStruct(english: "motivation", spanish: "motivación"),
        WordsStruct(english: "move", spanish: "jugada"),
        WordsStruct(english: "movie", spanish: "filme"),
        WordsStruct(english: "mushroom", spanish: "hongo"),
        WordsStruct(english: "musician", spanish: "músico"),
        WordsStruct(english: "my", spanish: "mi, mis"),
        WordsStruct(english: "myself", spanish: "yo mismo"),
        WordsStruct(english: "nail", spanish: "clavo"),
        WordsStruct(english: "name", spanish: "nombre"),
        WordsStruct(english: "nameless", spanish: "anónimo"),
        WordsStruct(english: "nation", spanish: "nación"),
        WordsStruct(english: "national", spanish: "nacional"),
        WordsStruct(english: "near", spanish: "cerca de"),
        WordsStruct(english: "nephew", spanish: "sobrino"),
        WordsStruct(english: "nest", spanish: "nido"),
        WordsStruct(english: "new", spanish: "nuevo"),
        WordsStruct(english: "next", spanish: "próximo"),
        WordsStruct(english: "nick", spanish: "muesca"),
        WordsStruct(english: "night", spanish: "noche"),
        WordsStruct(english: "nine", spanish: "nueve"),
        WordsStruct(english: "nineteen", spanish: "diecinueve"),
        WordsStruct(english: "nineteenth", spanish: "decimonono"),
        WordsStruct(english: "noise", spanish: "alboroto"),
        WordsStruct(english: "noisy", spanish: "ruidoso"),
        WordsStruct(english: "north", spanish: "norte"),
        WordsStruct(english: "notice", spanish: "aviso"),
        WordsStruct(english: "now", spanish: "ahora"),
        WordsStruct(english: "nylon", spanish: "nylon"),
        WordsStruct(english: "object", spanish: "objetivo"),
        WordsStruct(english: "oblivious", spanish: "olvidado"),
        WordsStruct(english: "observance", spanish: "observancia"),
        WordsStruct(english: "obstruct", spanish: "obstruir"),
        WordsStruct(english: "obvious", spanish: "obvio"),
        WordsStruct(english: "ocean", spanish: "océano"),
        WordsStruct(english: "odd", spanish: "impar"),
        WordsStruct(english: "off", spanish: "libre"),
        WordsStruct(english: "offer", spanish: "oferta"),
        WordsStruct(english: "office", spanish: "cargo"),
        WordsStruct(english: "offside", spanish: "fuera de juego"),
        WordsStruct(english: "often", spanish: "frecuentemente"),
        WordsStruct(english: "oil", spanish: "aceite"),
        WordsStruct(english: "old", spanish: "viejo"),
        WordsStruct(english: "omission", spanish: "omisión"),
        WordsStruct(english: "once", spanish: "antes"),
        WordsStruct(english: "oncology", spanish: "oncología"),
        WordsStruct(english: "onion", spanish: "cebolla"),
        WordsStruct(english: "only", spanish: "sólo"),
        WordsStruct(english: "open", spanish: "abierto"),
        WordsStruct(english: "operator", spanish: "telefonista"),
        WordsStruct(english: "opportunity", spanish: "oportunidad"),
        WordsStruct(english: "opposite", spanish: "contrario"),
        WordsStruct(english: "optimal", spanish: "óptimo"),
        WordsStruct(english: "optional", spanish: "facultativo"),
        WordsStruct(english: "or", spanish: "o"),
        WordsStruct(english: "orange", spanish: "naranja, naranjo"),
        WordsStruct(english: "orbit", spanish: "órbita"),
        WordsStruct(english: "order", spanish: "pedido"),
        WordsStruct(english: "organization", spanish: "organización"),
        WordsStruct(english: "organize", spanish: "organizar"),
        WordsStruct(english: "other", spanish: "otro"),
        WordsStruct(english: "our", spanish: "nuestro"),
        WordsStruct(english: "out", spanish: "fuera"),
        WordsStruct(english: "outside", spanish: "exterior"),
        WordsStruct(english: "oval", spanish: "óvalo"),
        WordsStruct(english: "overall", spanish: "total"),
        WordsStruct(english: "overdrive", spanish: "superdirecta"),
        WordsStruct(english: "overflow", spanish: "rebosadero"),
        WordsStruct(english: "owe", spanish: "deber"),
        WordsStruct(english: "owl", spanish: "búho"),
        WordsStruct(english: "own", spanish: "propio"),
        WordsStruct(english: "ox", spanish: "buey"),
        WordsStruct(english: "oxygen", spanish: "oxígeno"),
        WordsStruct(english: "oyster", spanish: "ostra"),
        WordsStruct(english: "pace", spanish: "marcha"),
        WordsStruct(english: "pack", spanish: "compresa"),
        WordsStruct(english: "package", spanish: "paquete"),
        WordsStruct(english: "packet", spanish: "paquete"),
        WordsStruct(english: "padding", spanish: "almohadilla"),
        WordsStruct(english: "page", spanish: "página"),
        WordsStruct(english: "pain", spanish: "dolor"),
        WordsStruct(english: "paint", spanish: "pintura"),
        WordsStruct(english: "pair", spanish: "yunta"),
        WordsStruct(english: "palace", spanish: "palacio"),
        WordsStruct(english: "paper", spanish: "papel"),
        WordsStruct(english: "paragraph", spanish: "párrafo"),
        WordsStruct(english: "parameter", spanish: "parámetro"),
        WordsStruct(english: "paramedic", spanish: "paramédico"),
        WordsStruct(english: "pardon", spanish: "indulto"),
        WordsStruct(english: "parent", spanish: "progenitor"),
        WordsStruct(english: "park", spanish: "parque"),
        WordsStruct(english: "parking", spanish: "aparcamiento"),
        WordsStruct(english: "parrot", spanish: "loro"),
        WordsStruct(english: "part", spanish: "papel"),
        WordsStruct(english: "participle", spanish: "participio"),
        WordsStruct(english: "past", spanish: "pasado"),
        WordsStruct(english: "paste", spanish: "pasta"),
        WordsStruct(english: "pasta", spanish: "pastas"),
        WordsStruct(english: "patent", spanish: "patente"),
        WordsStruct(english: "path", spanish: "senda"),
        WordsStruct(english: "patrol", spanish: "patrulla"),
        WordsStruct(english: "pay", spanish: "salario"),
        WordsStruct(english: "pea", spanish: "guisante"),
        WordsStruct(english: "peach", spanish: "melocotón"),
        WordsStruct(english: "peak", spanish: "cumbre"),
        WordsStruct(english: "pen", spanish: "pluma estilográfica, bolígrafo"),
        WordsStruct(english: "pencil", spanish: "lápiz"),
        WordsStruct(english: "penguin", spanish: "pingüino"),
        WordsStruct(english: "perform", spanish: "desempeñar"),
        WordsStruct(english: "permission", spanish: "autorización"),
        WordsStruct(english: "persuade", spanish: "convencer"),
        WordsStruct(english: "petrol", spanish: "gasolina"),
        WordsStruct(english: "pharmacy", spanish: "droguería"),
        WordsStruct(english: "phone", spanish: "teléfono"),
        WordsStruct(english: "photo", spanish: "foto"),
        WordsStruct(english: "photograph", spanish: "fotografía"),
        WordsStruct(english: "physicalq", spanish: "físico"),
        WordsStruct(english: "physics", spanish: "física"),
        WordsStruct(english: "physic", spanish: "medicina"),
        WordsStruct(english: "pianist", spanish: "pianist"),
        WordsStruct(english: "piano", spanish: "piano"),
        WordsStruct(english: "pick", spanish: "pico"),
        WordsStruct(english: "picture", spanish: "dibujo"),
        WordsStruct(english: "pie", spanish: "pastel"),
        WordsStruct(english: "piece", spanish: "fragmento"),
        WordsStruct(english: "pig", spanish: "poli"),
        WordsStruct(english: "pin", spanish: "alfiler"),
        WordsStruct(english: "pine-apple", spanish: "piña"),
        WordsStruct(english: "pitch", spanish: "tono"),
        WordsStruct(english: "place", spanish: "sitio"),
        WordsStruct(english: "plain", spanish: "vulgar"),
        WordsStruct(english: "plan", spanish: "proyecto"),
        WordsStruct(english: "plane", spanish: "avión"),
        WordsStruct(english: "platform", spanish: "cadalso"),
        WordsStruct(english: "play", spanish: "juego"),
        WordsStruct(english: "player", spanish: "jugador"),
        WordsStruct(english: "pleasant", spanish: "agradable"),
        WordsStruct(english: "please", spanish: "placer"),
        WordsStruct(english: "ploy", spanish: "estratagema"),
        WordsStruct(english: "plug", spanish: "espita"),
        WordsStruct(english: "plumb", spanish: "plomo"),
        WordsStruct(english: "plus", spanish: "más"),
        WordsStruct(english: "pocket", spanish: "hueco"),
        WordsStruct(english: "pod", spanish: "vaina"),
        WordsStruct(english: "podium", spanish: "podio"),
        WordsStruct(english: "poet", spanish: "poeta"),
        WordsStruct(english: "poem", spanish: "poema"),
        WordsStruct(english: "point", spanish: "punta"),
        WordsStruct(english: "poker", spanish: "atizador"),
        WordsStruct(english: "poor", spanish: "indigente"),
        WordsStruct(english: "population", spanish: "población"),
        WordsStruct(english: "pore", spanish: "poro"),
        WordsStruct(english: "portfolio", spanish: "cartera"),
        WordsStruct(english: "portion", spanish: "porción"),
        WordsStruct(english: "portrait", spanish: "retrato"),
        WordsStruct(english: "possible", spanish: "posible"),
        WordsStruct(english: "postcode", spanish: "código postal"),
        WordsStruct(english: "power", spanish: "energía"),
        WordsStruct(english: "practical", spanish: "práctico"),
        WordsStruct(english: "praise", spanish: "elogio"),
        WordsStruct(english: "prefer", spanish: "preferir"),
        WordsStruct(english: "push", spanish: "empujón"),
        WordsStruct(english: "put", spanish: "colocar"),
        WordsStruct(english: "put on", spanish: "ponerse"),
        WordsStruct(english: "python", spanish: "pitón"),
        WordsStruct(english: "quack", spanish: "graznido"),
        WordsStruct(english: "quad", spanish: "patio"),
        WordsStruct(english: "quadrant", spanish: "cuadrante"),
        WordsStruct(english: "quality", spanish: "calidad"),
        WordsStruct(english: "quantify", spanish: "cuantificar"),
        WordsStruct(english: "quarter", spanish: "dirección"),
        WordsStruct(english: "quartz", spanish: "cuarzo"),
        WordsStruct(english: "queen", spanish: "reina"),
        WordsStruct(english: "question", spanish: "pregunta"),
        WordsStruct(english: "quick", spanish: "carne"),
        WordsStruct(english: "quickly", spanish: "rápidamentea"),
        WordsStruct(english: "quid", spanish: "libra esterlina"),
        WordsStruct(english: "quiet", spanish: "silencio"),
        WordsStruct(english: "quit", spanish: "cesar"),
        WordsStruct(english: "quota", spanish: "cuota"),
        WordsStruct(english: "rabbit", spanish: "conejo"),
        WordsStruct(english: "race", spanish: "raza"),
        WordsStruct(english: "racecourse", spanish: "hipódromo"),
        WordsStruct(english: "racing", spanish: "carreras de cabellos"),
        WordsStruct(english: "racket", spanish: "raqueta"),
        WordsStruct(english: "radiator", spanish: "radiador"),
        WordsStruct(english: "radio", spanish: "radio"),
        WordsStruct(english: "radish", spanish: "rábano"),
        WordsStruct(english: "rail", spanish: "barra"),
        WordsStruct(english: "railway", spanish: "ferrocarril"),
        WordsStruct(english: "rain", spanish: "lluvia"),
        WordsStruct(english: "rainbow", spanish: "arco iris"),
        WordsStruct(english: "ramble", spanish: "paseo"),
        WordsStruct(english: "range", spanish: "fila"),
        WordsStruct(english: "rank", spanish: "lozano"),
        WordsStruct(english: "rapid", spanish: "rápido"),
        WordsStruct(english: "rarely", spanish: "raras veces"),
        WordsStruct(english: "rash", spanish: "erupción"),
        WordsStruct(english: "rate", spanish: "precio"),
        WordsStruct(english: "reaction", spanish: "reacción"),
        WordsStruct(english: "reactivate", spanish: "reactivar"),
        WordsStruct(english: "read", spanish: "leer"),
        WordsStruct(english: "ready", spanish: "preparado"),
        WordsStruct(english: "realism", spanish: "realismo"),
        WordsStruct(english: "reason", spanish: "causa"),
        WordsStruct(english: "receive", spanish: "aceptar"),
        WordsStruct(english: "reception", spanish: "acogida"),
        WordsStruct(english: "receptionist", spanish: "recepcionista"),
        WordsStruct(english: "recreate", spanish: "recrear"),
        WordsStruct(english: "recycle", spanish: "reciclar"),
        WordsStruct(english: "red", spanish: "rojo"),
        WordsStruct(english: "reference", spanish: "referencia"),
        WordsStruct(english: "reflex", spanish: "reflejo"),
        WordsStruct(english: "refractor", spanish: "telescopio de refracción"),
        WordsStruct(english: "regency", spanish: "regencia"),
        WordsStruct(english: "register", spanish: "registro"),
        WordsStruct(english: "relax", spanish: "descansar"),
        WordsStruct(english: "remind", spanish: "recordar"),
        WordsStruct(english: "require", spanish: "requerir"),
        WordsStruct(english: "reset", spanish: "reajustar"),
        WordsStruct(english: "rhythm", spanish: "rítmico"),
        WordsStruct(english: "rice", spanish: "arroz"),
        WordsStruct(english: "rich", spanish: "rico"),
        WordsStruct(english: "riddle", spanish: "enigma"),
        WordsStruct(english: "right", spanish: "derecho"),
        WordsStruct(english: "ring", spanish: "anillo"),
        WordsStruct(english: "road", spanish: "calle"),
        WordsStruct(english: "rock", spanish: "roca"),
        WordsStruct(english: "roll", spanish: "panecillo"),
        WordsStruct(english: "romance", spanish: "amorío"),
        WordsStruct(english: "root", spanish: "raíz"),
        WordsStruct(english: "rose", spanish: "rosa"),
        WordsStruct(english: "round", spanish: "tanda"),
        WordsStruct(english: "row", spanish: "pelea"),
        WordsStruct(english: "royal", spanish: "sobrejuanete"),
        WordsStruct(english: "ruff", spanish: "gorguera"),
        WordsStruct(english: "run", spanish: "manejo"),
        WordsStruct(english: "sabot", spanish: "zueco"),
        WordsStruct(english: "sad", spanish: "afligido"),
        WordsStruct(english: "sadden", spanish: "entristecer"),
        WordsStruct(english: "sadness", spanish: "tristeza"),
        WordsStruct(english: "safe", spanish: "caja de caudales, alacena"),
        WordsStruct(english: "safety", spanish: "seguro"),
        WordsStruct(english: "sail", spanish: "vela"),
        WordsStruct(english: "saint", spanish: "santo"),
        WordsStruct(english: "salad", spanish: "ensalada"),
        WordsStruct(english: "sale", spanish: "venta"),
        WordsStruct(english: "salt", spanish: "sal"),
        WordsStruct(english: "save", spanish: "parada"),
        WordsStruct(english: "say", spanish: "decir"),
        WordsStruct(english: "scale", spanish: "platillo"),
        WordsStruct(english: "scan", spanish: "escáner"),
        WordsStruct(english: "scanner", spanish: "escáner"),
        WordsStruct(english: "scholarship", spanish: "beca"),
        WordsStruct(english: "school", spanish: "banco"),
        WordsStruct(english: "science", spanish: "ciencia"),
        WordsStruct(english: "scientist", spanish: "científico"),
        WordsStruct(english: "score", spanish: "veintena"),
        WordsStruct(english: "screen", spanish: "mampara"),
        WordsStruct(english: "script", spanish: "guión"),
        WordsStruct(english: "scroll", spanish: "desplazar"),
        WordsStruct(english: "sea", spanish: "mar"),
        WordsStruct(english: "seafood", spanish: "marisco"),
        WordsStruct(english: "second", spanish: "instante"),
        WordsStruct(english: "secret", spanish: "secreto"),
        WordsStruct(english: "section", spanish: "parte"),
        WordsStruct(english: "see", spanish: "sede"),
        WordsStruct(english: "self", spanish: "uno mismo"),
        WordsStruct(english: "send", spanish: "enviar"),
        WordsStruct(english: "set", spanish: "fijo"),
        WordsStruct(english: "setting", spanish: "escenario"),
        WordsStruct(english: "seven", spanish: "siete"),
        WordsStruct(english: "shape", spanish: "forma"),
        WordsStruct(english: "share", spanish: "parte"),
        WordsStruct(english: "sharp", spanish: "afilado"),
        WordsStruct(english: "shelf", spanish: "estante"),
        WordsStruct(english: "shine", spanish: "brillo"),
        WordsStruct(english: "shoe", spanish: "zapato"),
        WordsStruct(english: "shoot", spanish: "retoño"),
        WordsStruct(english: "short", spanish: "bajo"),
        WordsStruct(english: "show", spanish: "espectáculo"),
        WordsStruct(english: "shut", spanish: "cerrado"),
        WordsStruct(english: "shy", spanish: "tirada"),
        WordsStruct(english: "sick", spanish: "enfermo"),
        WordsStruct(english: "simple", spanish: "ingenuo"),
        WordsStruct(english: "since", spanish: "desde"),
        WordsStruct(english: "sit", spanish: "estar sentado"),
        WordsStruct(english: "six", spanish: "seis"),
        WordsStruct(english: "sixteen", spanish: "dieciséis"),
        WordsStruct(english: "sixteenth", spanish: "decimosexto"),
        WordsStruct(english: "size", spanish: "tamaño"),
        WordsStruct(english: "ski", spanish: "esquí"),
        WordsStruct(english: "skirt", spanish: "falda"),
        WordsStruct(english: "sleep", spanish: "sueño"),
        WordsStruct(english: "small", spanish: "menudo"),
        WordsStruct(english: "smart", spanish: "elegante"),
        WordsStruct(english: "smile", spanish: "sonrisa"),
        WordsStruct(english: "smoke", spanish: "humo"),
        WordsStruct(english: "snake", spanish: "serpiente"),
        WordsStruct(english: "snail", spanish: "caracol"),
        WordsStruct(english: "sneak", spanish: "de reojo"),
        WordsStruct(english: "snow", spanish: "nieve"),
        WordsStruct(english: "soap", spanish: "jabón"),
        WordsStruct(english: "sofa", spanish: "sofá"),
        WordsStruct(english: "solution", spanish: "solución"),
        WordsStruct(english: "some", spanish: "algunos"),
        WordsStruct(english: "sometimes", spanish: "a veces "),
        WordsStruct(english: "specific", spanish: "específico"),
        WordsStruct(english: "speak", spanish: "hablar"),
        WordsStruct(english: "special", spanish: "especial"),
        WordsStruct(english: "speed", spanish: "prisa"),
        WordsStruct(english: "spring", spanish: "manantial"),
        WordsStruct(english: "stand", spanish: "grupo"),
        WordsStruct(english: "standard", spanish: "norma"),
        WordsStruct(english: "star", spanish: "estrella"),
        WordsStruct(english: "structure", spanish: "estructura"),
        WordsStruct(english: "student", spanish: "estudiante"),
        WordsStruct(english: "study", spanish: "despacho"),
        WordsStruct(english: "super", spanish: "fenomenal"),
        WordsStruct(english: "superman", spanish: "superhombre"),
        WordsStruct(english: "surfing", spanish: "surfing"),
        WordsStruct(english: "surprise", spanish: "sorpresa"),
        WordsStruct(english: "suspect", spanish: "sospechar"),
        WordsStruct(english: "swim", spanish: "baño"),
        WordsStruct(english: "swimmer", spanish: "nadador"),
        WordsStruct(english: "swipe", spanish: "golpear"),
        WordsStruct(english: "switch", spanish: "interruptor"),
        WordsStruct(english: "symbol", spanish: "símbolo"),
        WordsStruct(english: "symmetry", spanish: "simetría"),
        WordsStruct(english: "symphony", spanish: "sinfonía"),
        WordsStruct(english: "syntax", spanish: "sintaxis"),
        WordsStruct(english: "system", spanish: "sistema"),
        WordsStruct(english: "tab", spanish: "cuenta"),
        WordsStruct(english: "table", spanish: "mesa"),
        WordsStruct(english: "tactic", spanish: "táctica"),
        WordsStruct(english: "take", spanish: "recaudación"),
        WordsStruct(english: "tall", spanish: "alto"),
        WordsStruct(english: "tanager", spanish: "tángara"),
        WordsStruct(english: "target", spanish: "blanco"),
        WordsStruct(english: "taste", spanish: "gusto"),
        WordsStruct(english: "tea", spanish: "té"),
        WordsStruct(english: "teach", spanish: "enseñar"),
        WordsStruct(english: "telegraphy", spanish: "telegrafía"),
        WordsStruct(english: "tell", spanish: "distinguir"),
        WordsStruct(english: "territory", spanish: "territorio"),
        WordsStruct(english: "than", spanish: "que, de"),
        WordsStruct(english: "that", spanish: "ese"),
        WordsStruct(english: "their", spanish: "su, sus"),
        WordsStruct(english: "they", spanish: "ellos"),
        WordsStruct(english: "thin", spanish: "delgado"),
        WordsStruct(english: "three", spanish: "tres"),
        WordsStruct(english: "through", spanish: "completamente"),
        WordsStruct(english: "throw", spanish: "tirada"),
        WordsStruct(english: "tick", spanish: "garrapata"),
        WordsStruct(english: "ticket", spanish: "billete"),
        WordsStruct(english: "tidy", spanish: "limpio"),
        WordsStruct(english: "toast", spanish: "brindis"),
        WordsStruct(english: "today", spanish: "hoy"),
        WordsStruct(english: "together", spanish: "juntos"),
        WordsStruct(english: "toke", spanish: "calada"),
        WordsStruct(english: "tooth", spanish: "diente"),
        WordsStruct(english: "top", spanish: "trompo"),
        WordsStruct(english: "touch", spanish: "contacto"),
        WordsStruct(english: "tourist", spanish: "turista"),
        WordsStruct(english: "town", spanish: "ciudad"),
        WordsStruct(english: "track", spanish: "carril"),
        WordsStruct(english: "trade", spanish: "comercio"),
        WordsStruct(english: "tradition", spanish: "tradición"),
        WordsStruct(english: "train", spanish: "tren"),
        WordsStruct(english: "transformer", spanish: "transformador"),
        WordsStruct(english: "translation", spanish: "traducción"),
        WordsStruct(english: "true", spanish: "auténtico"),
        WordsStruct(english: "trust", spanish: "depósito"),
        WordsStruct(english: "try", spanish: "tentativa"),
        WordsStruct(english: "turn", spanish: "comportamiento"),
        WordsStruct(english: "twenty", spanish: "veinte"),
        WordsStruct(english: "two", spanish: "dos"),
        WordsStruct(english: "type", spanish: "tipo"),
        WordsStruct(english: "typical", spanish: "característico"),
        WordsStruct(english: "ultimate", spanish: "último"),
        WordsStruct(english: "unable", spanish: "incapaz"),
        WordsStruct(english: "unaccountable", spanish: "inexplicable"),
        WordsStruct(english: "unafraid", spanish: "sin miedo"),
        WordsStruct(english: "unanswered", spanish: "sin contestación"),
        WordsStruct(english: "unavailable", spanish: "no disponible"),
        WordsStruct(english: "under", spanish: "conforme"),
        WordsStruct(english: "underground", spanish: "subterráneo"),
        WordsStruct(english: "underline", spanish: "subrayar"),
        WordsStruct(english: "understand", spanish: "comprender"),
        WordsStruct(english: "unit", spanish: "unidad"),
        WordsStruct(english: "unite", spanish: "unir"),
        WordsStruct(english: "united", spanish: "unido"),
        WordsStruct(english: "university", spanish: "universidad"),
        WordsStruct(english: "unknown", spanish: "desconocido"),
        WordsStruct(english: "use", spanish: "uso"),
        WordsStruct(english: "used", spanish: "acostumbrado"),
        WordsStruct(english: "user", spanish: "usuario"),
        WordsStruct(english: "usual", spanish: "usual"),
        WordsStruct(english: "usually", spanish: "habitualmente"),
        WordsStruct(english: "vacancy", spanish: "vacancia"),
        WordsStruct(english: "vacation", spanish: "vacación"),
        WordsStruct(english: "vacuum", spanish: "vacío"),
        WordsStruct(english: "valley", spanish: "valle"),
        WordsStruct(english: "value", spanish: "valor"),
        WordsStruct(english: "vamper", spanish: "remendón"),
        WordsStruct(english: "various", spanish: "varios"),
        WordsStruct(english: "vegetable", spanish: "verdura"),
        WordsStruct(english: "vehicle", spanish: "vehículo"),
        WordsStruct(english: "venom", spanish: "veneno"),
        WordsStruct(english: "verification", spanish: "verificación"),
        WordsStruct(english: "view", spanish: "opinión"),
        WordsStruct(english: "villa", spanish: "villa"),
        WordsStruct(english: "visual", spanish: "visual"),
        WordsStruct(english: "voice", spanish: "voz"),
        WordsStruct(english: "void", spanish: "vacío"),
        WordsStruct(english: "volley", spanish: "descarga"),
        WordsStruct(english: "vote", spanish: "votación"),
        WordsStruct(english: "vowel", spanish: "vocal"),
        WordsStruct(english: "voyage", spanish: "travesía"),
        WordsStruct(english: "wait", spanish: "espera"),
        WordsStruct(english: "waiter", spanish: "camarero"),
        WordsStruct(english: "waitress", spanish: "camarera"),
        WordsStruct(english: "wake", spanish: "estela"),
        WordsStruct(english: "walk", spanish: "andadura"),
        WordsStruct(english: "wall", spanish: "muro"),
        WordsStruct(english: "wallet", spanish: "cartera"),
        WordsStruct(english: "want", spanish: "falta"),
        WordsStruct(english: "warm", spanish: "caliente"),
        WordsStruct(english: "wash", spanish: "ropa"),
        WordsStruct(english: "waster", spanish: "vago"),
        WordsStruct(english: "watch", spanish: "reloj"),
        WordsStruct(english: "water", spanish: "agua"),
        WordsStruct(english: "way", spanish: "camino"),
        WordsStruct(english: "we", spanish: "nosotros"),
        WordsStruct(english: "weak", spanish: "débil"),
        WordsStruct(english: "wear", spanish: "desgaste"),
        WordsStruct(english: "wedding", spanish: "boda"),
        WordsStruct(english: "weight", spanish: "peso"),
        WordsStruct(english: "welcome", spanish: "bienvenida"),
        WordsStruct(english: "well", spanish: "hueco"),
        WordsStruct(english: "west", spanish: "oeste"),
        WordsStruct(english: "western", spanish: "occidental"),
        WordsStruct(english: "wet", spanish: "bobo"),
        WordsStruct(english: "what", spanish: "lo que"),
        WordsStruct(english: "where", spanish: "dónde"),
        WordsStruct(english: "which", spanish: "cuál"),
        WordsStruct(english: "whose", spanish: "cuyo"),
        WordsStruct(english: "why", spanish: "por"),
        WordsStruct(english: "wife", spanish: "esposa"),
        WordsStruct(english: "will", spanish: "voluntad"),
        WordsStruct(english: "win", spanish: "victoria"),
        WordsStruct(english: "wood", spanish: "madera"),
        WordsStruct(english: "word", spanish: "palabra"),
        WordsStruct(english: "work", spanish: "obra"),
        WordsStruct(english: "world", spanish: "mundo"),
        WordsStruct(english: "worry", spanish: "inquietud"),
        WordsStruct(english: "worse", spanish: "peor"),
        WordsStruct(english: "wrap", spanish: "abrigo"),
        WordsStruct(english: "write", spanish: "escribir"),
        WordsStruct(english: "wrong", spanish: "malo"),
        WordsStruct(english: "xanthic", spanish: "xántico"),
        WordsStruct(english: "xenon", spanish: "xenón"),
        WordsStruct(english: "xenophobe", spanish: "xenófobo"),
        WordsStruct(english: "xenophobia", spanish: "xenofobia"),
        WordsStruct(english: "xylem", spanish: "leño"),
        WordsStruct(english: "xylograph", spanish: "grabado en madera"),
        WordsStruct(english: "xylographer", spanish: "xilógrafo"),
        WordsStruct(english: "xylography", spanish: "xilografía"),
        WordsStruct(english: "xylophonist", spanish: "xilofonista"),
        WordsStruct(english: "yap", spanish: "ladrido"),
        WordsStruct(english: "yard", spanish: "yarda"),
        WordsStruct(english: "year", spanish: "año"),
        WordsStruct(english: "yellow", spanish: "amarillo"),
        WordsStruct(english: "yes", spanish: "sí"),
        WordsStruct(english: "yesterday", spanish: "ayer"),
        WordsStruct(english: "yesternight", spanish: "anoche"),
        WordsStruct(english: "yet", spanish: "aún"),
        WordsStruct(english: "you", spanish: "tú"),
        WordsStruct(english: "young", spanish: "joven"),
        WordsStruct(english: "younger", spanish: "menor"),
        WordsStruct(english: "youngest", spanish: "el menor"),
        WordsStruct(english: "your", spanish: "tu, tus"),
        WordsStruct(english: "yourself", spanish: "tú mismo"),
        WordsStruct(english: "yourselves", spanish: "vosotros mismos"),
        WordsStruct(english: "youth", spanish: "juventud"),
        WordsStruct(english: "zap", spanish: "cargarse"),
        WordsStruct(english: "zebra", spanish: "cebra"),
        WordsStruct(english: "zero", spanish: "cero"),
        WordsStruct(english: "zombie", spanish: "zombi"),
        WordsStruct(english: "zone", spanish: "región"),
        WordsStruct(english: "zoo", spanish: "jardín zoológico"),
        WordsStruct(english: "zoography", spanish: "zoografía"),
        WordsStruct(english: "zoologist", spanish: "zoólogo"),
        WordsStruct(english: "zoology", spanish: "zoología"),
        WordsStruct(english: "zoom", spanish: "zoom"),
        WordsStruct(english: "zygote", spanish: "cigoto")
        
    ]
}




struct WordsStruct {
    let english: String
    let spanish: String
}
